# ********************************************************************************************************************************************
#   File Name: manage.py
#   Purpose:
#     * Sets the DJANGO_SETTINGS_MODULE environment variable so that it points to the project's settings.py file when using the command line
#     * Generated by 'django-admin startproject' using Django 4.1.6.
#     * For more information on this file, see https://docs.djangoproject.com/en/4.1/ref/django-admin/
# ********************************************************************************************************************************************

# Import statements
import os
import sys

def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "terrapin_tracker.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()