# Generated by Django 4.1.7 on 2023-03-07 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turtle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_num", models.IntegerField()),
                ("hatchling_num", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date(2023, 3, 7))),
                ("carapace_length", models.FloatField()),
                ("carapace_width", models.FloatField()),
                ("plastron_length", models.FloatField()),
                ("carapace_height", models.FloatField()),
                ("mass", models.FloatField()),
                (
                    "turtle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="turtles.turtle"
                    ),
                ),
            ],
        ),
    ]
