# Generated by Django 4.1.7 on 2023-03-16 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Turtle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_num", models.IntegerField(verbose_name="R Number")),
                ("hatchling_num", models.IntegerField(verbose_name="Hatchling Number")),
                (
                    "editor",
                    models.TextField(default="Administrator", verbose_name="Editor"),
                ),
                ("archived", models.BooleanField(blank=True, null=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid From"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid To"
                    ),
                ),
                (
                    "previous_turtle",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtles.turtle",
                        verbose_name="Previous Turtle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                (
                    "carapace_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Carapace Length"
                    ),
                ),
                (
                    "carapace_width",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Carapace Width"
                    ),
                ),
                (
                    "plastron_length",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Plastron Length"
                    ),
                ),
                (
                    "carapace_height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Carapace Height"
                    ),
                ),
                ("mass", models.FloatField(blank=True, null=True, verbose_name="Mass")),
                (
                    "editor",
                    models.TextField(default="Administrator", verbose_name="Editor"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid From"
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid To"
                    ),
                ),
                (
                    "previous_measurment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtles.measurement",
                        verbose_name="Previous Measurment",
                    ),
                ),
                (
                    "turtle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="turtles.turtle",
                        verbose_name="Turtle",
                    ),
                ),
            ],
        ),
    ]
