# Generated by Django 4.1.7 on 2023-03-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="editor",
            field=models.TextField(blank=True, null=True, verbose_name="Editor"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="editor",
            field=models.TextField(blank=True, null=True, verbose_name="Editor"),
        ),
    ]
