# Generated by Django 4.1.7 on 2023-03-07 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
