# Generated by Django 4.1.7 on 2023-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0002_alter_measurement_editor_alter_turtle_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turtle",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Valid From"
            ),
        ),
    ]
