# Generated by Django 4.1.7 on 2023-03-15 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0002_alter_measurement_valid_from_alter_turtle_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
    ]
