# Generated by Django 4.1.7 on 2023-03-13 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0002_alter_measurement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="editor",
            field=models.TextField(default="Administrator"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="measurement",
            name="valid_to",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="turtle",
            name="editor",
            field=models.TextField(default="Administrator"),
        ),
        migrations.AddField(
            model_name="turtle",
            name="valid_from",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="turtle",
            name="valid_to",
            field=models.DateTimeField(default=None),
        ),
    ]
