# Generated by Django 4.1.7 on 2023-03-16 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0003_alter_turtle_valid_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turtle",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="editor",
            field=models.TextField(default="Administrator", verbose_name="Editor"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
    ]
