# Generated by Django 4.1.7 on 2023-03-13 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0003_measurement_editor_measurement_valid_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="carapace_height",
            field=models.FloatField(verbose_name="Carapace Height"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="carapace_length",
            field=models.FloatField(verbose_name="Carapace Length"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="carapace_width",
            field=models.FloatField(verbose_name="Carapace Width"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="editor",
            field=models.TextField(default="Administrator", verbose_name="Editor"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="mass",
            field=models.FloatField(verbose_name="Mass"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="plastron_length",
            field=models.FloatField(verbose_name="Plastron Length"),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="turtle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="turtles.turtle",
                verbose_name="Turtle",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="valid_to",
            field=models.DateTimeField(default=None, verbose_name="Valid To"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="editor",
            field=models.TextField(default="Administrator", verbose_name="Editor"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="hatchling_num",
            field=models.IntegerField(verbose_name="Hatchling Number"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="r_num",
            field=models.IntegerField(verbose_name="R Number"),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Valid From"
            ),
        ),
        migrations.AlterField(
            model_name="turtle",
            name="valid_to",
            field=models.DateTimeField(default=None, verbose_name="Valid To"),
        ),
    ]
