# Generated by Django 4.1.7 on 2023-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turtles", "0004_alter_turtle_archived_alter_turtle_editor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="valid_from",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Valid From"
            ),
        ),
    ]
